blank_issues_enabled: false
contact_links:
  - name: Ask a question 
    url: https://github.com/runfinch/infrastructure/discussions
    about: Use GitHub Discussions to ask questions, discuss options, or propose new ideas